"""Create source table

Revision ID: e8e1013a9f00
Revises: b4633a698241
Create Date: 2025-12-13 19:36:05.709349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sqm


# revision identifiers, used by Alembic.
revision: str = "e8e1013a9f00"
down_revision: Union[str, Sequence[str], None] = "b4633a698241"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("update_id", sa.Integer(), nullable=False),
        sa.Column("title", sqm.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqm.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqm.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("credibility", sa.Float(), nullable=True),
        sa.Column("relevance", sa.Float(), nullable=True),
        sa.Column("reasoning", sqm.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["update_id"], ["predictionupdate.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_title"), "source", ["title"], unique=False)
    op.create_index(op.f("ix_source_url"), "source", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_url"), table_name="source")
    op.drop_index(op.f("ix_source_title"), table_name="source")
    op.drop_table("source")
    # ### end Alembic commands ###
