"""005 refactor fields optionality

Revision ID: 39492550011a
Revises: 0aff70acf5ea
Create Date: 2025-12-22 20:42:53.847080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39492550011a"
down_revision: Union[str, Sequence[str], None] = "0aff70acf5ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("predictionupdate") as batch_op:
        batch_op.alter_column("likelihood", existing_type=sa.FLOAT(), nullable=False)
    with op.batch_alter_table("predictionupdate") as batch_op:
        batch_op.alter_column("reasoning", existing_type=sa.VARCHAR(), nullable=False)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("summary", existing_type=sa.VARCHAR(), nullable=False)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("credibility", existing_type=sa.FLOAT(), nullable=False)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("relevance", existing_type=sa.FLOAT(), nullable=False)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("reasoning", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("reasoning", existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("relevance", existing_type=sa.FLOAT(), nullable=True)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("credibility", existing_type=sa.FLOAT(), nullable=True)
    with op.batch_alter_table("source") as batch_op:
        batch_op.alter_column("summary", existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table("predictionupdate") as batch_op:
        batch_op.alter_column("reasoning", existing_type=sa.VARCHAR(), nullable=True)
    with op.batch_alter_table("predictionupdate") as batch_op:
        batch_op.alter_column("likelihood", existing_type=sa.FLOAT(), nullable=True)
    # ### end Alembic commands ###
