"""006 create humanreview table

Revision ID: 989393577605
Revises: 39492550011a
Create Date: 2025-12-22 21:33:34.111090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel as sqm


# revision identifiers, used by Alembic.
revision: str = "989393577605"
down_revision: Union[str, Sequence[str], None] = "39492550011a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "humanreview",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("update_id", sa.Integer(), nullable=False),
        sa.Column("name", sqm.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("ACCEPT", "CHALLENGE", "REJECT", name="reviewdecision"),
            nullable=False,
        ),
        sa.Column("feedback", sqm.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["update_id"], ["predictionupdate.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("humanreview")
    # ### end Alembic commands ###
